name: e_track
description: "E Track"


publish_to: 'none'













version: 2.0.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter

#  flutter_background_service_android:
#    path: ./flutter_background_service-master/packages/flutter_background_service_android
#
#  flutter_background_service_ios:
#    path: ./flutter_background_service-master/packages/flutter_background_service_ios
#
#  flutter_background_service_platform_interface:
#    path: ./flutter_background_service-master/packages/flutter_background_service_platform_interface

  flutter_background_service:
    path: ./flutter_background_service-master/packages/flutter_background_service

  auto_start_flutter:
    path: ./auto_start_flutter-master

  google_maps_cluster_manager:
    git:
      url: https://github.com/MacDeveloper1/google_maps_cluster_manager.git
      ref: fix/cluster


  
  
  cupertino_icons: ^1.0.6
#  flutter_background_service: ^5.0.7
  flutter_local_notifications: ^17.2.2
  device_info_plus: ^10.1.2
  shared_preferences: ^2.2.3
  get: ^4.6.6
  dio: ^5.5.0+1
  get_storage: ^2.1.1
  google_fonts: ^6.2.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  json_serializable: ^6.6.1
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
  flutter_foreground_task: ^8.3.0
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  disable_battery_optimization: ^1.1.1
  encrypt: ^5.0.3
  email_validator: ^3.0.0
  analyzer: ^6.7.0
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  http_parser: ^4.0.2
  logger: ^2.4.0
  app_settings: ^5.1.1
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9





flutter:



  
  uses-material-design: true

  
  assets:
    - assets/images/icons/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
