// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'auth_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AuthResponse _$AuthResponseFromJson(Map<String, dynamic> json) => AuthResponse(
      status: json['status'] as bool?,
      message: json['message'] as String?,
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => AuthData.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$AuthResponseToJson(AuthResponse instance) =>
    <String, dynamic>{
      'status': instance.status,
      'message': instance.message,
      'data': instance.data,
    };

AuthData _$AuthDataFromJson(Map<String, dynamic> json) => AuthData(
      userId: json['user_id'] as String?,
      userCode: json['user_code'] as String?,
      userName: json['user_name'] as String?,
      firstName: json['first_name'] as String?,
      lastName: json['last_name'] as String?,
      email: json['email'] as String?,
      password: json['password'] as String?,
      mobileCode: json['mobile_code'] as String?,
      mobile: json['mobile'] as String?,
      profileImage: json['profile_image'] as String?,
      stateId: json['state_id'] as String?,
      districtId: json['district_id'] as String?,
      cityId: json['city_id'] as String?,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      areaName: json['areaName'] as String?,
      zipcode: json['zipcode'] as String?,
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      userType: json['user_type'] as String?,
      registerDate: json['register_date'] as String?,
      referralCode: json['referral_code'] as String?,
      walletBalance: json['wallet_balance'] as String?,
      notifyPref: json['notify_pref'] as String?,
      deviceType: json['deviceType'] as String?,
      deviceName: json['deviceName'] as String?,
      appVersion: json['appVersion'] as String?,
      deviceOs: json['deviceOs'] as String?,
      status: json['status'] as String?,
      dlNumber: json['dl_number'] as String?,
      dlFront: json['dl_front'] as String?,
      dlBack: json['dl_back'] as String?,
      isCorporate: json['is_corporate'] as String?,
      screenName: json['screenName'] as String?,
      busOrganisationId: json['bus_organisation_id'] as String?,
      busOrganisationBranchId: json['bus_organisation_branch_id'] as String?,
      busOrganisationRole: json['bus_organisation_role'] as String?,
      accessType: json['access_type'] as String?,
      parentId: json['parent_id'] as String?,
      isSlottedVehicleAnalysis: json['is_slotted_vehicle_analysis'] as String?,
      slotTime: json['slot_time'] as String?,
      selectedColumns: json['selected_columns'] as String?,
      tripSelectedColumns: json['trip_selected_columns'] as String?,
      isTofaTripData: json['is_tofa_trip_data'] as String?,
      isTrailerDashboard: json['is_trailer_dashboard'] as String?,
      mobileLaunchMode: json['mobile_launch_mode'] as String?,
      homeTab: json['home_tab'] as String?,
      mobileListType: json['mobile_list_type'] as String?,
      state: json['state'] as String?,
      districtName: json['district_name'] as String?,
      city: json['city'] as String?,
      registeredByType: json['registered_by_type'] as String?,
      registeredById: json['registered_by_id'] as String?,
      companyId: json['company_id'] as String?,
      companyName: json['company_name'] as String?,
      companyLogo: json['company_logo'] as String?,
      companyStateId: json['company_state_id'] as String?,
      companyDistrictId: json['company_district_id'] as String?,
      companyCityId: json['company_city_id'] as String?,
      companyAddress1: json['company_address1'] as String?,
      companyLandmark: json['company_landmark'] as String?,
      companyAddress2: json['company_address2'] as String?,
      companyPincode: json['company_pincode'] as String?,
      companyEmail: json['company_email'] as String?,
      companyMobile: json['company_mobile'] as String?,
      companyState: json['company_state'] as String?,
      companyDistrictName: json['company_district_name'] as String?,
      companyCity: json['company_city'] as String?,
    );

Map<String, dynamic> _$AuthDataToJson(AuthData instance) => <String, dynamic>{
      'user_id': instance.userId,
      'user_code': instance.userCode,
      'user_name': instance.userName,
      'first_name': instance.firstName,
      'last_name': instance.lastName,
      'email': instance.email,
      'password': instance.password,
      'mobile_code': instance.mobileCode,
      'mobile': instance.mobile,
      'profile_image': instance.profileImage,
      'state_id': instance.stateId,
      'district_id': instance.districtId,
      'city_id': instance.cityId,
      'address1': instance.address1,
      'address2': instance.address2,
      'areaName': instance.areaName,
      'zipcode': instance.zipcode,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'user_type': instance.userType,
      'register_date': instance.registerDate,
      'referral_code': instance.referralCode,
      'wallet_balance': instance.walletBalance,
      'notify_pref': instance.notifyPref,
      'deviceType': instance.deviceType,
      'deviceName': instance.deviceName,
      'appVersion': instance.appVersion,
      'deviceOs': instance.deviceOs,
      'status': instance.status,
      'dl_number': instance.dlNumber,
      'dl_front': instance.dlFront,
      'dl_back': instance.dlBack,
      'is_corporate': instance.isCorporate,
      'screenName': instance.screenName,
      'bus_organisation_id': instance.busOrganisationId,
      'bus_organisation_branch_id': instance.busOrganisationBranchId,
      'bus_organisation_role': instance.busOrganisationRole,
      'access_type': instance.accessType,
      'parent_id': instance.parentId,
      'is_slotted_vehicle_analysis': instance.isSlottedVehicleAnalysis,
      'slot_time': instance.slotTime,
      'selected_columns': instance.selectedColumns,
      'trip_selected_columns': instance.tripSelectedColumns,
      'is_tofa_trip_data': instance.isTofaTripData,
      'is_trailer_dashboard': instance.isTrailerDashboard,
      'mobile_launch_mode': instance.mobileLaunchMode,
      'home_tab': instance.homeTab,
      'mobile_list_type': instance.mobileListType,
      'state': instance.state,
      'district_name': instance.districtName,
      'city': instance.city,
      'registered_by_type': instance.registeredByType,
      'registered_by_id': instance.registeredById,
      'company_id': instance.companyId,
      'company_name': instance.companyName,
      'company_logo': instance.companyLogo,
      'company_state_id': instance.companyStateId,
      'company_district_id': instance.companyDistrictId,
      'company_city_id': instance.companyCityId,
      'company_address1': instance.companyAddress1,
      'company_landmark': instance.companyLandmark,
      'company_address2': instance.companyAddress2,
      'company_pincode': instance.companyPincode,
      'company_email': instance.companyEmail,
      'company_mobile': instance.companyMobile,
      'company_state': instance.companyState,
      'company_district_name': instance.companyDistrictName,
      'company_city': instance.companyCity,
    };
